### ISSUE TITLE
BitBucket Server webhook - error 500

### ISSUE THREAD

**Issue by LennyCastaneda** [aws-samples/aws-codepipeline-bitbucket-integration#1]
Hey Alex,

Thank you so much for putting out this type of solution for Bitbucket Server integration with CodePipeline. You're awesome for this!!!!!!

I followed your instructions in the documentation and used an API Gateway instead of a Load Balancer. And found a few errors on my end, so I could be doing something and if so please let me know.

In this create-stack command:
```
aws cloudformation create-stack --stack-name CodePipeline-Bitbucket-Integration --template-body file:///package.yaml --parameters file:///infra/parameters.json --capabilities CAPABILITY_NAMED_IAM
```
It would not work unless I removed a "/" from --parameters and --template argument's file path.

Removing them like below will allow the stack to be created.
```
aws cloudformation create-stack --stack-name CodePipeline-Bitbucket-Integration --template-body file://package.yaml --parameters file://infra/parameters.json --capabilities CAPABILITY_NAMED_IAM
```

After I made the above change and filled in the parameters.json file, CloudFormation successfully created the stack. From the AWs UI console I deployed the API Gateway: **CodePipeline-Bitbucket-Integration** and copied the endpoint URL and pasted it into my Bitbucket Server's repository webhook.

In my Bitbucket repository (which is running in the same VPC and same subnet that the Lambda has connection too) When testing the connection I got a status 200. But After I triggered a build by adding a comment to a commit, I got this response below.

_**Webhook event details**_

**REQUEST**

**HEADER**
X-Hub-Signature: sha256=7bb0ec6ef324a2a0637f740efdb6d1267e1ee44947c0f78bc48fef7fb300c31e
X-Request-Id: 27f2dfb5-912e-4246-af9b-f0e52d1eb281
Content-Type: application/json; charset=utf-8
X-Event-Key: repo:comment:added

**BODY:**
{"eventKey":"repo:comment:added","date":"2019-11-27T23:22:07+0000","actor":{"name":"xxxx","emailAddress":"xxxxxxxxx@gmail.com","id":1,"displayName":"Lenny Castaneda","active":true,"slug":"xxxxxx","type":"NORMAL","links":{"self":[{"href":"http://ec2-xxxxxxxxx.us-west-2.compute.amazonaws.com/users/xxxxxxxx"}]}},"comment":{"properties":{"repositoryId":13},"id":2,"version":0,"text":"Test comment #2","author":{"name":"xxxxx","emailAddress":"xxxxxxxxx@gmail.com","id":1,"displayName":"Lenny Castaneda","active":true,"slug":"xxxxxx","type":"NORMAL","links":{"self":[{"href":"http://xxxxxxxxxxx.us-west-2.compute.amazonaws.com/users/xxxxxxx"}]}},"createdDate":1574896927696,"updatedDate":1574896927696,"comments":[],"tasks":[],"severity":"NORMAL","state":"OPEN"},"repository":{"slug":"ami","id":13,"name":"AMI","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":true,"project":{"key":"xxxxx","id":1,"name":"xxxxxxx","description":"Devops Testing","public":false,"type":"NORMAL","links":{"self":[{"href":"http://xxxxxxxxx.compute.amazonaws.com/projects/xxxxxx"}]}},"public":false,"links":{"clone":[{"href":"ssh://git@xxxxxxx.us-west-2.compute.amazonaws.com:7999/xxxx/ami.git","name":"ssh"},{"href":"http://xxxxxxxxxx.us-west-2.compute.amazonaws.com/scm/xxx/ami.git","name":"http"}],"self":[{"href":"http://xxxxxxxxxxxx.us-west-2.compute.amazonaws.com/projects/xxxxx/repos/ami/browse"}]}},"commit":"6899921754f8ec3f5d05b68d77c6abe75783d41c"}

**RESPONSE:**

**HEADERS**
Access-Control-Allow-Origin: *
x-amzn-RequestId: d52f551a-36ca-4069-9380-178061b43e7c
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Content-Length: 54
Access-Control-Allow-Methods: POST, GET
X-Amzn-Trace-Id: Root=1-5ddf051f-413343e0556a3471887773fe;Sampled=0
Date: Wed, 27 Nov 2019 23:22:08 GMT
x-amz-apigw-id: D128-GLNPHcF1hQ=
Content-Type: application/json
Via: 1.1 localhost (Apache-HttpClient/4.5.5 (cache))
Connection: keep-alive

**BODY**
{"statusCode":500,"fault":"Some weird thing happened"}

Any help or guidance on how you got your internal Bitbucket Server to successfully send its webhook POST to the API Gateway I would be extra extra Thankful for. 

Looking forward to hear from you. Have a Happy Thanksgiving.

**Comment by alexfrosa** [comment]
Hi @LennyCastaneda thank you for pointing out the error when executing the "aws cloudformation create-stack" command. Your contribution is important. I will work with the blog team to fix that. 

About the error that you are getting, this is the default error when some exception happens during the Lambda function execution. You can find the details in the Lambda logs on CloudWatch. If you can post the error log here, I can take a look. 

This link provides instructions on how to access the Lambda log files. https://docs.aws.amazon.com/lambda/latest/dg/monitoring-functions-logs.html

**Comment by LennyCastaneda** [comment]
Thanks for your response @alexfrosa!!! 

Yes here is what the Lambda logs say for the latest trigger. See screen shot below.

Thank you again so much for your help.

![ Cloud Watch Logs](https://user-images.githubusercontent.com/9893446/69877175-546b9900-1276-11ea-9393-eff23cbad254.png)


```
7a901c15-1d87-44fd-aaff-5ab91c038a22	INFO	Exiting with error TypeError: Cannot read property '0' of undefined
    at Runtime.exports.handler (/var/task/index.js:27:32)
    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)
```

**Comment by alexfrosa** [comment]
Hi @LennyCastaneda the event example you sent is for a comment (repo:comment:added). The Lambda function is programmed to trigger only when you push code to the repo. Can you try to send a push to your repo and see if works?

If it doesn't work, please send the event logged on CloudWatch (it is logged in the beginning of the request) and the error message.

**Comment by LennyCastaneda** [comment]
Here is the log info after a push is made to the repo.

Looks like a timeout error.

```
4dcb60b3-21f7-4a30-bc95-d4ce40ee7c9d	INFO	info >>> downloadFile()

4dcb60b3-21f7-4a30-bc95-d4ce40ee7c9d	INFO	proxy: undefined

END RequestId: 4dcb60b3-21f7-4a30-bc95-d4ce40ee7c9d

REPORT RequestId: 4dcb60b3-21f7-4a30-bc95-d4ce40ee7c9d	Duration: 30030.18 ms	Billed Duration: 30000 ms	Memory Size: 128 MB	Max Memory Used: 96 MB	Init Duration: 388.05 ms	

2019-11-29T15:53:58.534Z 4dcb60b3-21f7-4a30-bc95-d4ce40ee7c9d Task timed out after 30.03 seconds

```

**Comment by LennyCastaneda** [comment]
REQUEST:

```
{
    "resource": "/",
    "path": "/",
    "httpMethod": "POST",
    "headers": {
        "Accept": "*/*",
        "Content-Type": "application/json; charset=UTF-8",
        "Host": "39a4eso0jd.execute-api.us-west-2.amazonaws.com",
        "User-Agent": "Atlassian HttpClient 2.1.0 / Bitbucket-6.8.0 (6008000) / Default",
        "Via": "1.1 localhost (Apache-HttpClient/4.5.5 (cache))",
        "X-Amzn-Trace-Id": "Root=1-5de13ef7-fc2d8a98a7c70fdc81f78818",
        "X-Event-Key": "repo:refs_changed",
        "X-Forwarded-For": "54.185.8.152",
        "X-Forwarded-Port": "443",
        "X-Forwarded-Proto": "https",
        "X-Hub-Signature": "sha256=defd98f802b2cb1b42401a43bba3dca02b86fdd39061a80ebeea07d342de13ae",
        "X-Request-Id": "49c19155-4e8f-42a5-929e-13354304ae36"
    },
    "multiValueHeaders": {
        "Accept": [
            "*/*"
        ],
        "Content-Type": [
            "application/json; charset=UTF-8"
        ],
        "Host": [
            "39a4eso0jd.execute-api.us-west-2.amazonaws.com"
        ],
        "User-Agent": [
            "Atlassian HttpClient 2.1.0 / Bitbucket-6.8.0 (6008000) / Default"
        ],
        "Via": [
            "1.1 localhost (Apache-HttpClient/4.5.5 (cache))"
        ],
        "X-Amzn-Trace-Id": [
            "Root=1-5de13ef7-fc2d8a98a7c70fdc81f78818"
        ],
        "X-Event-Key": [
            "repo:refs_changed"
        ],
        "X-Forwarded-For": [
            "54.185.8.152"
        ],
        "X-Forwarded-Port": [
            "443"
        ],
        "X-Forwarded-Proto": [
            "https"
        ],
        "X-Hub-Signature": [
            "sha256=defd98f802b2cb1b42401a43bba3dca02b86fdd39061a80ebeea07d342de13ae"
        ],
        "X-Request-Id": [
            "49c19155-4e8f-42a5-929e-13354304ae36"
        ]
    },
    "queryStringParameters": null,
    "multiValueQueryStringParameters": null,
    "pathParameters": null,
    "stageVariables": null,
    "requestContext": {
        "resourceId": "nm0exbzfy2",
        "resourcePath": "/",
        "httpMethod": "POST",
        "extendedRequestId": "D7bGuHKqvHcF3BQ=",
        "requestTime": "29/Nov/2019:15:53:27 +0000",
        "path": "/prod",
        "accountId": "716857163627",
        "protocol": "HTTP/1.1",
        "stage": "prod",
        "domainPrefix": "39a4eso0jd",
        "requestTimeEpoch": 1575042807785,
        "requestId": "972f669d-4c9a-4971-989f-c9c26c93c693",
        "identity": {
            "cognitoIdentityPoolId": null,
            "accountId": null,
            "cognitoIdentityId": null,
            "caller": null,
            "sourceIp": "54.185.8.152",
            "principalOrgId": null,
            "accessKey": null,
            "cognitoAuthenticationType": null,
            "cognitoAuthenticationProvider": null,
            "userArn": null,
            "userAgent": "Atlassian HttpClient 2.1.0 / Bitbucket-6.8.0 (6008000) / Default",
            "user": null
        },
        "domainName": "39a4eso0jd.execute-api.us-west-2.amazonaws.com",
        "apiId": "39a4eso0jd"
    },
```

**Comment by LennyCastaneda** [comment]
Here is what it looks like on my Bitbucker Server side when I test the webhook against the endpoint.

REQUEST
![Webhook Request](https://user-images.githubusercontent.com/9893446/69880631-4bcb9080-127f-11ea-8ab7-64c0c8b85f07.png)

RESPONSE
![Webhook Response](https://user-images.githubusercontent.com/9893446/69880643-538b3500-127f-11ea-90c1-0dc0c686354b.png)

**Comment by alexfrosa** [comment]
> Here is the log info after a push is made to the repo.
> 
> Looks like a timeout error.
> 
> ```
> 4dcb60b3-21f7-4a30-bc95-d4ce40ee7c9d	INFO	info >>> downloadFile()
> 
> 4dcb60b3-21f7-4a30-bc95-d4ce40ee7c9d	INFO	proxy: undefined
> 
> END RequestId: 4dcb60b3-21f7-4a30-bc95-d4ce40ee7c9d
> 
> REPORT RequestId: 4dcb60b3-21f7-4a30-bc95-d4ce40ee7c9d	Duration: 30030.18 ms	Billed Duration: 30000 ms	Memory Size: 128 MB	Max Memory Used: 96 MB	Init Duration: 388.05 ms	
> 
> 2019-11-29T15:53:58.534Z 4dcb60b3-21f7-4a30-bc95-d4ce40ee7c9d Task timed out after 30.03 seconds
> ```

Yes, it timed out. The most common reason is the Lambda function has not been able to connect to the Bitbucket server. Some items to check:
1) Confirm that the VPC/Subnet where the Lambda is configured has routing and access to the Bitbucket server IP. 
2) Check the security group associated with the Bitbucket server. It should allow traffic to the Bitbucket server port  coming from the Lambda function

**Comment by LennyCastaneda** [comment]
Thanks @alexfrosa .

Ok so Lambda and Bitbucket server are in the same VPC and same private subnets. When I provisioned Lambda from the Cloudformation params template I added the only two private subnets to Lambda, one of which these private subnets is where BitBucket server is running on.

Now I just added the HTTP inbound rule to the Bitbucket security group. And we have successful download of zipfile. Thank you.

After downloading the zip file I noticed my repo does not contain the submodules in it...I think I'll need to do a clone instead. If we were to refactor the Lambda function in the index.js file, the only async function that would need to change is downloadFile(), correct?   ...I wonder what it looks like behind the scenes in Lambda's container to download/install git, clone repo, then run 'git submodule update --init' to download the latest submodules.

How would you go about cloning the repo to pull in the submodules? I appreciate your expert opinion.

**Comment by alexfrosa** [comment]
> Thanks @alexfrosa .
> 
> Ok so Lambda and Bitbucket server are in the same VPC and same private subnets. When I provisioned Lambda from the Cloudformation params template I added the only two private subnets to Lambda, one of which these private subnets is where BitBucket server is running on.
> 
> Now I just added the HTTP inbound rule to the Bitbucket security group. And we have successful download of zipfile. Thank you.
> 
> After downloading the zip file I noticed my repo does not contain the submodules in it...I think I'll need to do a clone instead. If we were to refactor the Lambda function in the index.js file, the only async function that would need to change is downloadFile(), correct? ...I wonder what it looks like behind the scenes in Lambda's container to download/install git, clone repo, then run 'git submodule update --init' to download the latest submodules.
> 
> How would you go about cloning the repo to pull in the submodules? I appreciate your expert opinion.

Correct, you need to modify the downloadFile function. You probably need to add code to get the submodule list from the repository, download the code of each submodule, merge it and then generate a new zip file before sending it to the S3 bucket. Just some thoughts, maybe there is a more efficient way to do it.
