### ISSUE TITLE
BitBucket Server Unreachable while connecting 

### ISSUE THREAD

**Issue by rajddas** [aws-samples/aws-codepipeline-bitbucket-integration#10]
Hey Alex,

It's really a wonderful solution which has almost taken care of our problem to include Bitbucket Server to CodePipeline.

Everything was working as expected. But suddenly we got this below mentioned error while connecting to API Gateway from Bitbucket.

ERROR : "The server didn't respond you may retry when it comes back up". Please refer to the screenshot for better explanation.

Not able to figure out where it is failing as the event is not coming to the API gateway itself. Is it a Bitbucket Server Firewall error or there is a problem with the API Gateway endpoint which was working absolutely fine till last week.
<img width="940" alt="Bitbucket-error" src="https://user-images.githubusercontent.com/56073921/81326624-bba83780-90b7-11ea-9851-76a20333e35e.png">

Please Note that we are using Enterprise Bamboo Server and our AWS VPC has connection to on-prem bitbucket server with Transit Gateway and my Lambda function is running on a specific VPC to be able to download the code from Bitbucket.

**Comment by alexfrosa** [comment]
Hi @rajddas it seems like the request is not reaching the API Gateway. Could you check the API Gateway and Lambda logs?

**Comment by rajddas** [comment]
Ya Alex, in my API gateway logs and metrics no data have been populated. We are currently in touch with the Bitbucket Server team, lets see what they have to say.

**Comment by manojreddygmr** [comment]
Hi,

I am facing the same issue
Did you get any resolution.

Thanks!!
Manoj

**Comment by rajddas** [comment]
Yes, It was an issue with the bitbucket server. Increase these properties : 

plugin.webhooks.io.threads
plugin.webhooks.dispatch.queue.size
plugin.webhooks.http.connection.host.max

It should solve the issue.

**Comment by manojreddygmr** [comment]
Thank you!!!
It worked

**Comment by rajddas** [comment]
As its resolved. Closing the issue.
