### ISSUE TITLE
Getting 403 Error during creation of LambdaFunction

### ISSUE THREAD

**Issue by askurat** [aws-samples/aws-codepipeline-bitbucket-integration#11]
I am getting an error during the creation of the LamdaFunction:

> Your access has been denied by S3, please make sure your request credentials have permission to GetObject for lexlabs3bucketmgmtapps/f4a779b4953357ca1517a6a0e76994f4. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 25909cf8-1365-4872-a6ad-b4e6f21d2001)

The account I am using has full admin access. Not really sure what to check.

Thanks,
Tony

**Comment by alexfrosa** [comment]
Hi Tony, you are probably using the package.yaml that comes with the source code and points to this bucket lexlabs3bucketmgmtapps. Make sure you execute this command before deployment to generate a new package.yaml for your environment.

aws cloudformation package --template-file ./infra/infra.yaml --s3-bucket your_bucket_name --output-template-file package.yaml

**Comment by askurat** [comment]
Thanks @alexfrosa. That worked, however while testing it I am getting the following error in the Lambda function:

> Cannot find module './node_modules/axios'

**Comment by askurat** [comment]
Apparently, I forgot how to read today. I completely missed the part where I needed to npm install from the code directory. Its been a day. Thanks again, Alex.

**Comment by alexfrosa** [comment]
I'm glad you were able to resolve the issue.
