### ISSUE TITLE
License inconsistent

### ISSUE THREAD

**Issue by davur** [aws-samples/aws-codepipeline-bitbucket-integration#12]
Is the license: 

MIT License as per `LICENSE` file - https://github.com/aws-samples/aws-codepipeline-bitbucket-integration/blob/3c3392c0a3a4ece07e3cadd051314ddbf1fc774b/LICENSE#L1

or

Apache 2.0 as per `package.json` - https://github.com/aws-samples/aws-codepipeline-bitbucket-integration/blob/3c3392c0a3a4ece07e3cadd051314ddbf1fc774b/code/package.json#L7

**Comment by alexfrosa** [comment]
Hi @davur, thank you for point this out. It is now fixed.

**Comment by davur** [comment]
👍
