### ISSUE TITLE
Bitbucket webhook is failing to upload the source code to api gateway

### ISSUE THREAD

**Issue by dstewart25** [aws-samples/aws-codepipeline-bitbucket-integration#13]
Whenever I push a change to my Bitbucket repository, the webhook fails with this error:
`java.lang.RuntimeException: java.net.SocketTimeoutException: 20,000 milliseconds timeout on connection http-outgoing-3 [ACTIVE]`

**Comment by alexfrosa** [comment]
Hi @dstewart25 it seems like there is a connectivity issue between your Bitbucket server and the AWS endpoint (ALB or API Gateway). Check if the Bitbucket server has access to your endpoint.

**Comment by dstewart25** [comment]
Thank you for pointing me in the right direction. I found out that the Lambda function did not have access to the internet. I opened up the VPC to the internet and that fixed the problem.
