### ISSUE TITLE
Missing Output for API GW?

### ISSUE THREAD

**Issue by Marakai** [aws-samples/aws-codepipeline-bitbucket-integration#2]
It would be useful if the URL of the API GW would also be added to the Output, if used. Right now it seems only the ELB case is in the template.

As per the blog it says

```
Fill out the URL field with the API Gateway or Load Balancer URL. To obtain this URL, choose the Outputs tab of the AWS CloudFormation stack.
```

(currently putting this in myself, so may just send a PR)

**Comment by Marakai** [comment]
I suppose adding

```
 ProdDataEndpoint:
    Condition: EndpointTypeAPIGW
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
```

to the `Outputs` is a quick solution?

**Comment by alexfrosa** [comment]
> I suppose adding
> 
> ```
>  ProdDataEndpoint:
>     Condition: EndpointTypeAPIGW
>     Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
> ```
> 
> to the `Outputs` is a quick solution?

Hi @Marakai , thank you for sending this out. Your solution is correct, please submit a PR.
