### ISSUE TITLE
The CF template uses a lambda which runs on Node Js 14.x runtime which is already deprecated. Can you guys please update this to Node 20.x 

### ISSUE THREAD

**Issue by ramya-h** [aws-samples/aws-codepipeline-bitbucket-integration#26]
The CF template uses a lambda which runs on Node Js 14.x runtime which is already deprecated. Can you guys please update this to Node 20.x .

As of now I have tried running it with Node 16.x and it worked after adding the  axios and crypto, which are dependent packages of the lambda.
code provided via blog is in V2 SDK
Can you please refactor the code for V3 SDK and migrate to NodeJs 20.x

**Comment by cjgordon** [comment]
Had a similar issue - just updated the lambda code to support node 20.x, see:
https://github.com/aws-samples/aws-codepipeline-bitbucket-integration/pull/29

**Comment by alexfrosa** [comment]
Thanks for your contribution
