### ISSUE TITLE
Question: Why do we need an option for Application Load Balancer?

### ISSUE THREAD

**Issue by konstantinvlasenko** [aws-samples/aws-codepipeline-bitbucket-integration#3]
What is the reason to have an optional Load Balancer? In which cases API Gateway is not enough?

**Comment by alexfrosa** [comment]
> What is the reason to have an optional Load Balancer? In which cases API Gateway is not enough?

Hi @konstantinvlasenko , thank you for your question. 

Some customers just prefer to use an internal LB and restrict access to their internal network instead of using a private VPC endpoint for API Gateway and concern about setting policies on it.

**Comment by konstantinvlasenko** [comment]
Interesting.
Thank you!
