### ISSUE TITLE
S3 Bucket Error

### ISSUE THREAD

**Issue by AmitThakkar** [aws-samples/aws-codepipeline-bitbucket-integration#7]
We are deploying the stack in eu-central-1 region, and getting below error:

Error occurred while GetObject. S3 Error Code: PermanentRedirect. S3 Error Message: The bucket is in this region: us-east-1. Please use this region to retry the request (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 4deba866-40a6-40b8-9a10-612291cf533e)

**Comment by vikashkumarcr7** [comment]
how did you overcome this issue? i am getting the same error. can u please help?
